### ISSUE TITLE
Workflows stuck on "EXECUTING" status

### ISSUE THREAD

**Issue by gBuff** [frikky/Shuffle#15]
I've been installing and trying to play with the app these past hours and all my workflows (on the "on prem" version from your git) are stuck with : **Status: EXECUTING**

The same workflows are working on the cloud-based version, and (when used) my webhooks are functionning (and returning correct data when posting).

My last try was a basic "Hello World" workflow, which is also stuck. 
Is there anything I missed that I'll need to configure ? 

I also have some questions about the "Environments" and the possible multitenancy, do you prefer me to send you a mail about these ? 

Anyway, thank you very much because this project seems really cool and I'll try to put some effort on it :) !

**Comment by cerebraljam** [comment]
The "Hello World" example didn't work for me as well. While looking at the docker logs, I could see the following:

`shuffle-orborus | 2020/05/22 00:45:45 Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40`

**Comment by frikky** [comment]
Hey guys! Glad to hear you got to the point of executing, and that you tried the cloud version too.

There are a few possible issues here:
* Wrong target IP for worker/app_sdk. They are NOT part of the Shuffle Docker network, meaning this is expected. Right now, they replicate whatever hostname/IP is 
* What @cerebraljam said - Wrong docker version. This used to be an issue, but the variable
* Wrong environments - If you have the default one, "Shuffle", this shouldn't be an issue.

Please do the following to start of:
1. Change "OUTER_HOSTNAME" in .env to your IP or hostname. This is supposed to reflect the server hostname.
2. Restart docker-compose: 
```
docker-compose down 
docker-compose up -d
```

Working on a workaround so that it works out of the box right now :)

**Comment by frikky** [comment]
I've pushed new versions of Orborus and Worker to Dockerhub that take into account the networks they can and can't reach. Get them and try again: 
```
docker-compose down
docker pull frikky/shuffle:orborus
docker pull frikky/shuffle:worker
docker-compose up -d
```

**Comment by gBuff** [comment]
Thanks for your answer :) 

I've downloaded the new images but still not work. Problem is very likely due to my custom environments. 
Related issue is that I can't delete created environment (I tried to play with possible multitenancy).

I'll try to step up a bit on the docker architecture behind so I can be more helpful when pointing out issues ;)

**Comment by frikky** [comment]
@cerebraljam did you play get it to work after doing these changes?

**Comment by gBuff** [comment]
I still have the same issue after the changes : 

2020/05/22 09:31:22 Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40
2020/05/22 09:31:22 Failed checking worker 1dcf49c4-fc26-45b5-b7a7-e6dbf23b8b6d

**Comment by frikky** [comment]
Might be because of your local docker version not matching the Go version I've built the image with. 

Open up docker-compose.yml, and change orborus to this (adding the environment variable)

`
![issue 15 image](https://user-images.githubusercontent.com/5719530/82660561-e30c1200-9c2a-11ea-86b8-472f42fe1911.png)
`

Then restart docker-compose (restart directly doesn't work):
```
docker-compose down
docker-compose up
```

**Comment by gBuff** [comment]
Almost OK : it is passing for the orborus, but not for the workers : 

```
2020/05/22 11:15:35 Setting up worker environment
2020/05/22 11:15:35 Actions: 1
2020/05/22 11:15:35 Image: frikky/shuffle:testing_1.0.0
2020/05/22 11:15:35 hello_world:b9482991-69ec-43f6-921e-2121a610d1d7 has no status result yet. Should execute.
2020/05/22 11:15:35 Time to execute b9482991-69ec-43f6-921e-2121a610d1d7 with app testing:1.0.0, function hello_world, env Shuffle with 0 parameters.
2020/05/22 11:15:35 Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40
2020/05/22 11:15:35 Failed deploying testing_1-0-0_b9482991-69ec-43f6-921e-2121a610d1d7_ddaa1b42-c283-4466-ad25-83d903e606e4 from image frikky/shuffle:testing_1.0.0: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40
2020/05/22 11:15:35 Should send status and exit the entire thing?
2020/05/22 11:15:35 Status: EXECUTING, Results: 0, actions: 1
```

I'll take a look on how to set the DOCKER_API_VERSION globaly as a temp fix !

**Comment by gBuff** [comment]
For information, my docker version : 

```
root@poc-debian:~/shuffle# docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:25 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by gBuff** [comment]
I don't know if that might help on your side : 

https://stackoverflow.com/questions/51028784/can-i-pin-docker-api-version-client-version-1-38-is-too-new-maximum-supported

**Comment by frikky** [comment]
Fixed it in the latest orborus, passing the docker version down to the worker. Run

```
docker stop shuffle-orborus
docker pull frikky/shuffle:orborus
docker-compose restart
```

**Comment by gBuff** [comment]
\O/ ! It works ! 
I had to do a git pull for your information ! 
(keep the DOCKER_API_VERSION set in the docker-compose.yml should have been enough) 

Thanks :)

**Comment by wanhl1990** [comment]
@frikky Hi, I am running Shuffle in docker， but it also hang on  **Executing Workflow** . I follow this [https://shuffler.io/docs/getting_started](url) ， but it still not works。 Please give me a  help， thanks a lot.

- docker version
`
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:57:35 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:56:55 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

`

- workflow configuration
![image](https://user-images.githubusercontent.com/13211025/102183741-47edc900-3ee9-11eb-896a-9dcc7a14c3fe.png)

- it turnaround always but not execution.
![image](https://user-images.githubusercontent.com/13211025/102183813-6a7fe200-3ee9-11eb-9594-83f55f14d225.png)

- backend logs , it logs **_execute onprem with execution environment "Shuffle"_**, but I don't see anywhere to set it.  In the '.env' file, it set by default.
`
2020/12/15 07:25:03 [INFO] Starting execution of c5e3d4dd-b291-485f-b043-a4332e2e9748!
2020/12/15 07:25:03 Running POST execution with data {"execution_argument":"","start":"3bb5c112-1460-44aa-8bb4-0b4438c38e51"}
2020/12/15 07:25:03 [INFO] Should start execution on node 3bb5c112-1460-44aa-8bb4-0b4438c38e51
2020/12/15 07:25:03 [INFO] No execution source (trigger) specified. Setting to default
2020/12/15 07:25:03 [INFO] New startnode: 3bb5c112-1460-44aa-8bb4-0b4438c38e51
2020/12/15 07:25:03 [INFO] Executing ORG: 83857280-e721-4e66-895b-349851964cdb
2020/12/15 07:25:03 [FIXME] ImageNames to check: []string{"frikky/shuffle:Testing_1.0.0"}
2020/12/15 07:25:03 [INFO] Execution: 69b4df6d-9df5-4556-83c0-d0a0cb784678 should execute onprem with execution environment "Shuffle"
`

**Comment by frikky** [comment]
Hey @wanhl1990! Been a long time since I saw this. No configuration/editing should be necessary. Could you run this for me to help debug please?
```
docker logs shuffle-orborus
```

**Comment by wanhl1990** [comment]
- docker logs shuffle-orborus

```
2020/12/15 09:08:03 [WARNING] RUNNING_MODE not set - defaulting to Docker (NOT Kubernetes).
2020/12/15 09:08:03 [INFO] Setting up execution environment
2020/12/15 09:08:03 [INFO] Cleanup process running every 600 seconds
2020/12/15 09:08:03 [INFO] Running towards http://192.168.0.5:5001 with Org Shuffle
2020/12/15 09:08:03 [INFO] Setting up Docker environment. Downloading worker and App SDK!
2020/12/15 09:08:03 [INFO] Pulling image ghcr.io/frikky/shuffle-app_sdk:0.8.0
2020/12/15 09:08:03 [INFO] Looking for old containers
{"status":"Pulling from frikky/shuffle-app_sdk","id":"0.8.0"}
{"status":"Digest: sha256:37aed68bb2a42a93945f83aa0bc204563efcc90ba7d4b6c248bf0bda91a34089"}
{"status":"Status: Image is up to date for ghcr.io/frikky/shuffle-app_sdk:0.8.0"}
2020/12/15 09:08:06 [INFO] Successfully downloaded and built ghcr.io/frikky/shuffle-app_sdk:0.8.0
2020/12/15 09:08:06 [INFO] Pulling image ghcr.io/frikky/shuffle-worker:0.8.0
{"status":"Pulling from frikky/shuffle-worker","id":"0.8.0"}
{"status":"Digest: sha256:1084a01746b863cddfda52048f61ebc3e3ffad5811458c85ee12d8bf8447bae3"}
{"status":"Status: Image is up to date for ghcr.io/frikky/shuffle-worker:0.8.0"}
2020/12/15 09:08:08 [INFO] Successfully downloaded and built ghcr.io/frikky/shuffle-worker:0.8.0
2020/12/15 09:08:08 [INFO] Finished configuring docker environment
2020/12/15 09:08:08 [INFO] Waiting for executions at http://192.168.0.5:5001/api/v1/workflows/queue
2020/12/15 09:08:23 [INFO] cbe48b1d-0f99-4233-a7e6-94fd3f5b856b is deployed and to be removed from queue.
2020/12/15 09:08:23 [INFO] Found container ID b72c5900b6eeba0c22dd113b98e424d88cbfbf7eb1b71f49d925cdf3e98e5f4d
2020/12/15 09:08:23 Identifier: worker-cbe48b1d-0f99-4233-a7e6-94fd3f5b856b
2020/12/15 09:08:24 [INFO] Container 64917509e9bdcbbf76563153765bcd1837c528338594b9ed923976486daa1367 was created under environment Shuffle
2020/12/15 09:18:09 [INFO] Looking for old containers
2020/12/15 09:18:09 [INFO] NAME: /worker-cbe48b1d-0f99-4233-a7e6-94fd3f5b856b
2020/12/15 09:28:13 [INFO] Looking for old containers
2020/12/15 09:28:13 [INFO] NAME: /worker-cbe48b1d-0f99-4233-a7e6-94fd3f5b856b
2020/12/15 09:38:17 [INFO] Looking for old containers
2020/12/15 09:48:20 [INFO] Looking for old containers
2020/12/15 09:58:24 [INFO] Looking for old containers
2020/12/15 10:08:27 [INFO] Looking for old containers
```

**Comment by frikky** [comment]
Hey! Sorry I didn't get back to you earlier. This seems to be an issue within the apps itself, so you'll have to help me out a bit more. We'll follow the [debugging steps here.](https://shuffler.io/docs/configuration#debugging)

So when you executed, it created this line:
```
2020/12/15 09:08:24 [INFO] Container 64917509e9bdcbbf76563153765bcd1837c528338594b9ed923976486daa1367 was created under environment Shuffle
```

This means at least Orborus works, and it created a "Worker" container. Worker is the one controlling the workflow itself, which again starts apps. Could you try following the [debug steps](https://shuffler.io/docs/configuration#debugging) and send the logs from both the Worker AND the Apps the Worker starts?

I know this is tedious, so we're working on a solution to make it less so.

**Comment by wanhl1990** [comment]
> tedious

Hi,sorry about too late to reply.  I run it in a new env, Shuffle seems working well.   -,- .

Does shuffle need to connect google service ? My previous  env cannot to connect google .  I can't think of anything else, it's too strange.

Thanks verrrry much for your help .

**Comment by wanhl1990** [comment]
@frikky  Hi,sorry about too late to reply. I run it in a new env, Shuffle seems working well. -,- .

Does shuffle need to connect google service ? My previous env cannot to connect google . I can't think of anything else, it's too strange.

Thanks verrrry much for your help .

**Comment by frikky** [comment]
Oh, thats so weird - sorry for the inconvenience.

About google service: no, but the database in use is a google database (datastore) running locally. Its inside the shuffle-database container. This means you can run the whole thing in google easily tho 🙂
