### ISSUE TITLE
General exception: local variable 'newvalue' referenced before assignment

### ISSUE THREAD

**Issue by 219liangyi** [frikky/Shuffle#534]
![image](https://user-images.githubusercontent.com/19781251/136926560-0d1ae1b8-8a47-47f9-876f-f683e767da6a.png)

email app 
No matter how I use the email app, I will report an error. In addition, I always encounter this error in my daily use. How can I solve it? How to check?

**Comment by frikky** [comment]
Hey! 

This has been fixed in the App SDK. Please force update your apps. Thanks for the report!

**Comment by 219liangyi** [comment]
Force Update  apps ,The problem remains
![image](https://user-images.githubusercontent.com/19781251/140941382-a239c701-a000-4288-aff3-54b952ee88b9.png)
![image](https://user-images.githubusercontent.com/19781251/140941341-5738a299-b210-4232-bba6-c7bdfc7a5d26.png)
