### ISSUE TITLE
Issue working with variables

### ISSUE THREAD

**Issue by freyntjens** [frikky/Shuffle#777]
Hi,

Currently testing shuffle to see if it could be useful for our SOC.
Really struggling on something that should be quite simple i.e. using variables from another node. 

![image](https://user-images.githubusercontent.com/86711799/160435813-a24db74b-602f-441d-b333-1ecdc4c4b4cf.png)

Really simple workflow with 2 nodes that "repeat back to me". the fist one has the following json to execute:
{"name": "Fred","product": {"name": "Shuffle"}}

While running the workflow, it parses correctly the json but I'm unable to use the variables on node two as they don´t appear hence hovering the start node doesn't highlight it in "orange":

![image](https://user-images.githubusercontent.com/86711799/160436739-729961f0-a537-4928-b5dc-6e01ed32d70c.png)

They only appear if I select the execution argument:

![image](https://user-images.githubusercontent.com/86711799/160437130-5182d3bf-b7e6-419c-8b8b-7aaae772538d.png)

Really sorry annoying you guys for an apparently simple thing, but really struggling with this.
Any help would be appreciated.

Thanks

Fred

**Comment by frikky** [comment]
Hey! This is a visual bug, and is fixed in later versions (e.g. try nightly in your docker-compose). Good luck :)

PS: Nice name Fred

- Fred

**Comment by freyntjens** [comment]
Hi Frikky

Thanks for the swift update!
Did what you told bit the issue still remains :-(

![image](https://user-images.githubusercontent.com/86711799/160555908-cb9dd176-607d-435c-927b-10d9bc7968ca.png)
 On the execution I have the following logs:

Variables

call: {"name": "Fred","product": {"name": "Shuffle"}}

shuffle_action_logs: 2022-03-29 09:12:24,137 - HelloWorld - INFO - [WARNING] Failed parsing action as JSON (init): the JSON object must be str, bytes or bytearray, not dict. NOT important if running apps with webserver 2022-03-29 09:12:24,137 - HelloWorld - INFO - [DEBUG] Action: 2022-03-29 09:12:24,137 - HelloWorld - INFO - [DEBUG] Normal execution (env var). Action is a string. 2022-03-29 09:12:24,137 - HelloWorld - INFO - [DEBUG] Sending starting action result (EXECUTING). Param replace: False 2022-03-29 09:12:24,137 - HelloWorld - INFO - [DEBUG] NO EXECUTION - LOADING! 2022-03-29 09:12:24,137 - HelloWorld - INFO - [DEBUG] Before FULLEXEC stream result 2022-03-29 09:12:24,142 - HelloWorld - INFO - [DEBUG] AFTER FULLEXEC stream result (init) 2022-03-29 09:12:24,142 - HelloWorld - INFO - [DEBUG] Fixing branch return as object -> string 2022-03-29 09:12:24,142 - HelloWorld - INFO - [DEBUG] No authentication specified! 2022-03-29 09:12:24,142 - HelloWorld - INFO - [DEBUG] Pre parameters 2022-03-29 09:12:24,142 - HelloWorld - INFO - [DEBUG] Pre-loading parameters 2022-03-29 09:12:24,142 - HelloWorld - INFO - [DEBUG] Parameter variant: STATIC_VALUE 2022-03-29 09:12:24,143 - HelloWorld - INFO - Type of value: <class 'str'> 2022-03-29 09:12:24,158 - HelloWorld - INFO - [DEBUG] CHECKING multi execution list: 0! 2022-03-29 09:12:24,158 - HelloWorld - INFO - [DEBUG] OUTER VALUE: 2022-03-29 09:12:24,158 - HelloWorld - INFO - [DEBUG] Returned with newparams of length 1 2022-03-29 09:12:24,158 - HelloWorld - INFO - [INFO] Running normal execution (not loop) 2022-03-29 09:12:24,158 - HelloWorld - INFO - [DEBUG] Not in coroutine (1) 2022-03-29 09:12:24,158 - HelloWorld - INFO - [INFO] Returned from execution with type(s) <class 'str'> 2022-03-29 09:12:24,158 - HelloWorld - INFO - [INFO] Handling return as string of length 47 2022-03-29 09:12:24,158 - HelloWorld - INFO - [INFO] POST NEWRES RESULT! 2022-03-29 09:12:24,158 - HelloWorld - DEBUG - [DEBUG] Executed Start_node-5fb129ed-0750-417a-98e8-ef8715ae0779 2022-03-29 09:12:24,158 - HelloWorld - WARNING - [INFO] Action result ran with Magic parser output. 2022-03-29 09:12:24,158 - HelloWorld - INFO - [DEBUG] Already JSON-like. Returning from magic 2022-03-29 09:12:24,159 - HelloWorld - INFO - [DEBUG] Inside Send result with status SUCCESS 2022-03-29 09:12:24,159 - HelloWorld - INFO - [DEBUG] Before last stream result 2022-03-29 09:12:24,159 - HelloWorld - INFO - [INFO] URL FOR RESULT (URL): http://shuffle-backend:5001/api/v1/streams 

Any ideas?
Without being able to work with variables makes the testing useless...

Thanks

Fred

**Comment by frikky** [comment]
Please run all three
